package:
  name: sml
  version: "0.1.0"

source:
  git_rev: v0.1.0
  git_url: https://github.com/liuyenting/sml.git

requirements:
  build:
    - python
  run:
    - python
about:
  home: https://github.com/liuyenting/sml
  license: Apache 2.0
  license_file: LICENSE
